### ISSUE TITLE
Issues parsing Cisco ASA syslog

### ISSUE THREAD

**Issue by jacobsonesk2** [stoerr/GrokConstructor#32]
Error message: Grok pattern name NAGIOSTIME unknown at %{NAGIOSTIME}

Time: Tue Jan 23 20:18:28 UTC 2018

RequestId: null

Request Info:
ReqInfo for 5a67989400ff02fa9d279f64620001737e67726f6b636f6e7374727563746f7200013600010102 : {
  "_url":"/do/automatic",
  "groklibs":[
    "firewalls",
    "grok-patterns"
  ],
  "loglines":[
    "<166>Jan 23 2018 14:07:36: %ASA-6-302021: Teardown ICMP connection for faddr 10.29.250.193/0 gaddr 172.19.122.36/0 laddr 172.19.122.36/0 (ejacobson) type 3 code 3 "
  ],
  "submit":[
    "Go!"
  ]
}

Grok pattern name NAGIOSTIME unknown at %{NAGIOSTIME}
	at net.stoerr.grokconstructor.GrokPatternLibrary$$anonfun$replacePatterns$1$$anonfun$apply$mcVI$sp$1.apply(GrokPatternLibrary.scala:60)
	at net.stoerr.grokconstructor.GrokPatternLibrary$$anonfun$replacePatterns$1$$anonfun$apply$mcVI$sp$1.apply(GrokPatternLibrary.scala:57)
	at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:473)
	at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:473)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.util.matching.Regex.replaceAllIn(Regex.scala:473)
	at net.stoerr.grokconstructor.GrokPatternLibrary$$anonfun$replacePatterns$1.apply$mcVI$sp(GrokPatternLibrary.scala:56)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at net.stoerr.grokconstructor.GrokPatternLibrary$.replacePatterns(GrokPatternLibrary.scala:52)
	at net.stoerr.grokconstructor.automatic.AutomaticDiscoveryView$$anonfun$namedRegexps$1.apply(AutomaticDiscoveryView.scala:23)
	at net.stoerr.grokconstructor.automatic.AutomaticDiscoveryView$$anonfun$namedRegexps$1.apply(AutomaticDiscoveryView.scala:22)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at net.stoerr.grokconstructor.automatic.AutomaticDiscoveryView.namedRegexps$lzycompute(AutomaticDiscoveryView.scala:22)
	at net.stoerr.grokconstructor.automatic.AutomaticDiscoveryView.namedRegexps(AutomaticDiscoveryView.scala:22)
	at net.stoerr.grokconstructor.automatic.AutomaticDiscoveryView.namedRegexpsList$lzycompute(AutomaticDiscoveryView.scala:25)
	at net.stoerr.grokconstructor.automatic.AutomaticDiscoveryView.namedRegexpsList(AutomaticDiscoveryView.scala:25)
	at net.stoerr.grokconstructor.automatic.AutomaticDiscoveryView.matchingRegexpStructures(AutomaticDiscoveryView.scala:94)
	at net.stoerr.grokconstructor.automatic.AutomaticDiscoveryView.matchingRegexpStructures(AutomaticDiscoveryView.scala:92)
	at net.stoerr.grokconstructor.automatic.AutomaticDiscoveryView.result(AutomaticDiscoveryView.scala:59)
	at net.stoerr.grokconstructor.webframework.WebView$class.body(WebView.scala:34)
	at net.stoerr.grokconstructor.webframework.WebViewWithHeaderAndSidebox.body(WebViewWithHeaderAndSidebox.scala:10)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:60)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:33)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:680)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:642)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:612)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:455)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:462)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:321)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:313)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:459)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)

**Comment by stoerr** [comment]
OK, that's probably the grok pattern library being too old.

**Comment by stoerr** [comment]
I have now updated the grok pattern library, so NAGIOSTIME is certainly there now. But I just noticed that this bug occurs anyway, if you deselect the nagios pattern library for the automatic construction. OK, one more fix left.

**Comment by stoerr** [comment]
OK, done. The problem was that NAGIOSTIME was used in the firewall pattern set and is defined in a the deselected nagios pattern library. But that was an implementation problem in grokconstructor; that's now permitted.
