### ISSUE TITLE
Site crashes after trying to parse HTTP requests

### ISSUE THREAD

**Issue by cs-tim-buecher** [stoerr/GrokConstructor#34]
Hi Hans-Peter,

unfortunately the page crashes every time when I'm trying to use the constructor and try to parse logfiles. Especially when it comes to HTTP Requests. The failure I'm getting is:

Error message: com.google.apphosting.api.DeadlineExceededException: This request (cf19023660eb3df5) started at 2018/04/30 07:24:49.902 UTC and was still executing at 2018/04/30 07:25:49.868 UTC.

Time: Mon Apr 30 07:25:49 UTC 2018

RequestId: null

Request Info:
ReqInfo for 5ae6c4c100ff0db951fe23c62b0001737e67726f6b636f6e7374727563746f7200013600010101 : {
  "_url":"/do/constructionstep",
  "groklibs":[
    "firewalls",
    "aws",
    "bro",
    "exim",
    "bind",
    "haproxy",
    "linux-syslog",
    "squid",
    "mcollective-patterns",
    "bacula",
    "postgresql",
    "java",
    "maven",
    "grok-patterns",
    "httpd",
    "redis",
    "nagios",
    "rails",
    "mongodb",
    "ruby",
    "mcollective",
    "junos"
  ],
  "loglines":[
    "\"GET ....
  ],
  "nextPart":[
    "%{WORD}"
  ],
  "pattern":[
    "\\A\"",
    "\\A\""
  ],
  "submit":[
    "Continue!"
  ]
}

com.google.apphosting.api.DeadlineExceededException: This request (cf19023660eb3df5) started at 2018/04/30 07:24:49.902 UTC and was still executing at 2018/04/30 07:25:49.868 UTC.
	at org.joni.ByteCodeMachine.matchAt(ByteCodeMachine.java:254)
	at org.joni.Matcher.matchInterruptible(Matcher.java:113)
	at org.joni.Matcher.match(Matcher.java:94)
	at net.stoerr.grokconstructor.JoniRegex.matchStartOf(JoniRegex.scala:34)
	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$5$$anonfun$6.apply(IncrementalConstructionStepView.scala:35)
	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$5$$anonfun$6.apply(IncrementalConstructionStepView.scala:35)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$5.apply(IncrementalConstructionStepView.scala:35)
	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$5.apply(IncrementalConstructionStepView.scala:33)
	at scala.collection.immutable.List.map(List.scala:277)
	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView.(IncrementalConstructionStepView.scala:33)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.giveView(WebDispatcher.scala:81)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:53)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:33)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:686)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:648)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:618)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:455)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:462)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:321)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:313)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:459)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)

**Comment by stoerr** [comment]
Hi!
 

That happens when the algorithm takes too many resources. Unfortunately, I cannot do much about that - I'm currently out of ideas how to improve that. Did you follow the guideline to put in several loglines that are as different as possible? That reduces the search space and might help. Unfortunately I can't see that in your excerpt.

 

Best regards,

 

Hans-Peter

 




Gesendet: Montag, 30. April 2018 um 09:31 Uhr
Von: "Tim Bücher" <notifications@github.com>
An: stoerr/GrokConstructor <GrokConstructor@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [stoerr/GrokConstructor] Site crashes after trying to parse HTTP requests (#34)


Hi Hans-Peter,

unfortunately the page crashes every time when I'm trying to use the constructor and try to parse logfiles. Especially when it comes to HTTP Requests. The failure I'm getting is:

Error message: com.google.apphosting.api.DeadlineExceededException: This request (cf19023660eb3df5) started at 2018/04/30 07:24:49.902 UTC and was still executing at 2018/04/30 07:25:49.868 UTC.

Time: Mon Apr 30 07:25:49 UTC 2018

RequestId: null

Request Info:
ReqInfo for 5ae6c4c100ff0db951fe23c62b0001737e67726f6b636f6e7374727563746f7200013600010101 : {
"_url":"/do/constructionstep",
"groklibs":[
"firewalls",
"aws",
"bro",
"exim",
"bind",
"haproxy",
"linux-syslog",
"squid",
"mcollective-patterns",
"bacula",
"postgresql",
"java",
"maven",
"grok-patterns",
"httpd",
"redis",
"nagios",
"rails",
"mongodb",
"ruby",
"mcollective",
"junos"
],
"loglines":[
""GET ....
],
"nextPart":[
"%{WORD}"
],
"pattern":[
"\A"",
"\A""
],
"submit":[
"Continue!"
]
}

com.google.apphosting.api.DeadlineExceededException: This request (cf19023660eb3df5) started at 2018/04/30 07:24:49.902 UTC and was still executing at 2018/04/30 07:25:49.868 UTC.
at org.joni.ByteCodeMachine.matchAt(ByteCodeMachine.java:254)
at org.joni.Matcher.matchInterruptible(Matcher.java:113)
at org.joni.Matcher.match(Matcher.java:94)
at net.stoerr.grokconstructor.JoniRegex.matchStartOf(JoniRegex.scala:34)
at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$5$$anonfun$6.apply(IncrementalConstructionStepView.scala:35)
at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$5$$anonfun$6.apply(IncrementalConstructionStepView.scala:35)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
at scala.collection.AbstractTraversable.map(Traversable.scala:104)
at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$5.apply(IncrementalConstructionStepView.scala:35)
at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$5.apply(IncrementalConstructionStepView.scala:33)
at scala.collection.immutable.List.map(List.scala:277)
at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView.(IncrementalConstructionStepView.scala:33)
at net.stoerr.grokconstructor.webframework.WebDispatcher.giveView(WebDispatcher.scala:81)
at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:53)
at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:33)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:686)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:648)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:618)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:455)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:462)
at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:321)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:313)
at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:459)
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
at java.lang.Thread.run(Thread.java:745)

**Comment by stoerr** [comment]
Thank you for reporting this!

I cannot do anything about this since here the algorithm just takes too long - the only thing you can do is to add more log lines since that makes the search space smaller. But it should have a sensible error message, of course. But to clean up, I'm closing this one since that's the same problem as https://github.com/stoerr/GrokConstructor/issues/35 and would be fixed at the same time.
