### ISSUE TITLE
SGE

### ISSUE THREAD

**Issue by jafarncp** [stoerr/GrokConstructor#35]
During construction of SGE accounting log the web page is timed out and undermentioned error shows up:

OUCH!
I'm sorry, but you have encountered a bug or missing nice display of an error message in the application. If you can't guess the problem from the error message, please contact Hans-Peter Störr (www.stoerr.net yu4cheem@techno.ms) with a copy of this page, or open an issue on https://github.com/stoerr/GrokConstructor/issues .

Please remember that you can always press the back button to fix what was wrong - there is no state on the server, only in the page shown in the browser.

      

Error message: com.google.apphosting.api.DeadlineExceededException: This request (14dd6d2ba955f8fe) started at 2018/07/06 06:05:23.273 UTC and was still executing at 2018/07/06 06:06:23.193 UTC.

Time: Fri Jul 06 06:06:23 UTC 2018

RequestId: null

Request Info:
ReqInfo for 5b3f06a300ff041ebb9dd680e60001737e67726f6b636f6e7374727563746f7200013600010104 : {
  "_url":"/do/match",
  "groklibs":[
    "firewalls",
    "aws",
    "bro",
    "exim",
    "bind",
    "haproxy",
    "linux-syslog",
    "squid",
    "mcollective-patterns",
    "bacula",
    "postgresql",
    "java",
    "maven",
    "grok-patterns",
    "httpd",
    "redis",
    "nagios",
    "rails",
    "mongodb",
    "ruby",
    "mcollective",
    "junos"
  ],
  "loglines":[
    "all.q:compute-0-0.local:shanawer:shanawer:serial.sh:180:sge:0:1424235565:1424235576:1424235610:0:1:34:336.030915:0.335948:749624.000000:\r\n0:0:0:0:56445:0:0:3296.000000:35344:0:0:0:1176:1072:NONE:defaultdepartment:NONE:1:0:336.366863:7004.945530:0.014643:-q all.q:0.000000:\r\nNONE:22813732864.000000:0:0"
  ],
  "pattern":[
    "%{DATA:qname}:%{DATA:exehost}:%{DATA:group}:%{DATA:owner}:%{DATA:job_name}:%{DATA:job_number}:%{DATA:account}:%{DATA:priority}:%{INT:submission_time}:%{INT:start_time}:%{INT:end_time}:%{DATA:failed}:%{INT:exit_status}:%{INT:ru_wallclock:int}:%{DATA:ru_utime:float}:%{DATA:ru_stime:float}:%{DATA:ru_maxrss:float}:%{DATA:ru_ixrss}:%{DATA:ru_ismrss}:%{DATA:ru_idrss}:%{DATA:ru_isrss}:%{DATA:ru_minflt}:%{DATA:ru_majflt}:%{DATA:ru_nswap}:%{DATA:ru_inblock}:%{DATA:ru_oublock}:%{DATA:ru_msgsnd}:%{DATA:ru_msgrcv}:%{DATA:ru_nsignals}:%{DATA:ru_nvcsw:int}:%{DATA:ru_nivcsw:int}:%{DATA:project}:%{DATA:department}:%{DATA:granted_pe}:%{INT:slots:int}:%{DATA:task_number}:%{DATA:cpu:float}:%{DATA:mem:float}:%{DATA:io:float}:%{DATA:category}:%{DATA:iow:float}:%{DATA:pe_taskid}:%{DATA:maxvmem:int}:%{DATA:arid}:%{DATA:ar_sub_time}\r\n"
  ],
  "submit":[
    "Go!"
  ]
}

com.google.apphosting.api.DeadlineExceededException: This request (14dd6d2ba955f8fe) started at 2018/07/06 06:05:23.273 UTC and was still executing at 2018/07/06 06:06:23.193 UTC.
	at org.joni.ByteCodeMachine.opFail(ByteCodeMachine.java:1753)
	at org.joni.ByteCodeMachine.opExact1(ByteCodeMachine.java:428)
	at org.joni.ByteCodeMachine.matchAt(ByteCodeMachine.java:203)
	at org.joni.Matcher.matchCheck(Matcher.java:304)
	at org.joni.Matcher.searchInterruptible(Matcher.java:480)
	at org.joni.Matcher.search(Matcher.java:318)
	at net.stoerr.grokconstructor.JoniRegex.findIn(JoniRegex.scala:72)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$net$stoerr$grokconstructor$matcher$MatcherEntryView$$longestMatchOfRegexPrefix$1.apply(MatcherEntryView.scala:127)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$net$stoerr$grokconstructor$matcher$MatcherEntryView$$longestMatchOfRegexPrefix$1.apply(MatcherEntryView.scala:127)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
	at scala.collection.immutable.Stream.filter(Stream.scala:519)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView.net$stoerr$grokconstructor$matcher$MatcherEntryView$$longestMatchOfRegexPrefix(MatcherEntryView.scala:127)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$showResult$1.apply(MatcherEntryView.scala:76)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$showResult$1.apply(MatcherEntryView.scala:71)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView.showResult(MatcherEntryView.scala:71)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$result$1.apply(MatcherEntryView.scala:61)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$result$1.apply(MatcherEntryView.scala:61)
	at scala.Option.map(Option.scala:146)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView.result(MatcherEntryView.scala:61)
	at net.stoerr.grokconstructor.webframework.WebView$class.body(WebView.scala:34)
	at net.stoerr.grokconstructor.webframework.WebViewWithHeaderAndSidebox.body(WebViewWithHeaderAndSidebox.scala:10)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:60)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:33)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:693)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:655)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:625)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:455)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:462)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:321)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:313)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:459)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)

Any needful help or idea to build the requirements

Regards,

--jafar

**Comment by stoerr** [comment]
Hi!

That kind of error occurs, when there are too many possibilities to continue the pattern, so that the program gets a timeout when trying to collect all of them. I can't do anything about that, but you can: you can follow the advice to not only give one log line but several different log lines that all should match the pattern you create. 

Best regards,

Hans-Peter


Am 6. Juli 2018 08:19:59 MESZ schrieb jafarncp <notifications@github.com>:
>During construction of SGE accounting log the web page is timed out and
>undermentioned error shows up:
>
>
>OUCH!
>I'm sorry, but you have encountered a bug or missing nice display of an
>error message in the application. If you can't guess the problem from
>the error message, please contact Hans-Peter Störr (www.stoerr.net
>yu4cheem@techno.ms) with a copy of this page, or open an issue on
>https://github.com/stoerr/GrokConstructor/issues .
>
>Please remember that you can always press the back button to fix what
>was wrong - there is no state on the server, only in the page shown in
>the browser.
>
>      
>
>Error message: com.google.apphosting.api.DeadlineExceededException:
>This request (14dd6d2ba955f8fe) started at 2018/07/06 06:05:23.273 UTC
>and was still executing at 2018/07/06 06:06:23.193 UTC.
>
>Time: Fri Jul 06 06:06:23 UTC 2018
>
>RequestId: null
>
>Request Info:
>ReqInfo for
>5b3f06a300ff041ebb9dd680e60001737e67726f6b636f6e7374727563746f7200013600010104
>: {
>  "_url":"/do/match",
>  "groklibs":[
>    "firewalls",
>    "aws",
>    "bro",
>    "exim",
>    "bind",
>    "haproxy",
>    "linux-syslog",
>    "squid",
>    "mcollective-patterns",
>    "bacula",
>    "postgresql",
>    "java",
>    "maven",
>    "grok-patterns",
>    "httpd",
>    "redis",
>    "nagios",
>    "rails",
>    "mongodb",
>    "ruby",
>    "mcollective",
>    "junos"
>  ],
>  "loglines":[
>"all.q:compute-0-0.local:shanawer:shanawer:serial.sh:180:sge:0:1424235565:1424235576:1424235610:0:1:34:336.030915:0.335948:749624.000000:\r\n0:0:0:0:56445:0:0:3296.000000:35344:0:0:0:1176:1072:NONE:defaultdepartment:NONE:1:0:336.366863:7004.945530:0.014643:-q
>all.q:0.000000:\r\nNONE:22813732864.000000:0:0"
>  ],
>  "pattern":[
>"%{DATA:qname}:%{DATA:exehost}:%{DATA:group}:%{DATA:owner}:%{DATA:job_name}:%{DATA:job_number}:%{DATA:account}:%{DATA:priority}:%{INT:submission_time}:%{INT:start_time}:%{INT:end_time}:%{DATA:failed}:%{INT:exit_status}:%{INT:ru_wallclock:int}:%{DATA:ru_utime:float}:%{DATA:ru_stime:float}:%{DATA:ru_maxrss:float}:%{DATA:ru_ixrss}:%{DATA:ru_ismrss}:%{DATA:ru_idrss}:%{DATA:ru_isrss}:%{DATA:ru_minflt}:%{DATA:ru_majflt}:%{DATA:ru_nswap}:%{DATA:ru_inblock}:%{DATA:ru_oublock}:%{DATA:ru_msgsnd}:%{DATA:ru_msgrcv}:%{DATA:ru_nsignals}:%{DATA:ru_nvcsw:int}:%{DATA:ru_nivcsw:int}:%{DATA:project}:%{DATA:department}:%{DATA:granted_pe}:%{INT:slots:int}:%{DATA:task_number}:%{DATA:cpu:float}:%{DATA:mem:float}:%{DATA:io:float}:%{DATA:category}:%{DATA:iow:float}:%{DATA:pe_taskid}:%{DATA:maxvmem:int}:%{DATA:arid}:%{DATA:ar_sub_time}\r\n"
>  ],
>  "submit":[
>    "Go!"
>  ]
>}
>
>
>com.google.apphosting.api.DeadlineExceededException: This request
>(14dd6d2ba955f8fe) started at 2018/07/06 06:05:23.273 UTC and was still
>executing at 2018/07/06 06:06:23.193 UTC.
>	at org.joni.ByteCodeMachine.opFail(ByteCodeMachine.java:1753)
>	at org.joni.ByteCodeMachine.opExact1(ByteCodeMachine.java:428)
>	at org.joni.ByteCodeMachine.matchAt(ByteCodeMachine.java:203)
>	at org.joni.Matcher.matchCheck(Matcher.java:304)
>	at org.joni.Matcher.searchInterruptible(Matcher.java:480)
>	at org.joni.Matcher.search(Matcher.java:318)
>	at net.stoerr.grokconstructor.JoniRegex.findIn(JoniRegex.scala:72)
>	at
>net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$net$stoerr$grokconstructor$matcher$MatcherEntryView$$longestMatchOfRegexPrefix$1.apply(MatcherEntryView.scala:127)
>	at
>net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$net$stoerr$grokconstructor$matcher$MatcherEntryView$$longestMatchOfRegexPrefix$1.apply(MatcherEntryView.scala:127)
>	at
>scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
>	at
>scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
>	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
>	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
>	at scala.collection.immutable.Stream.filter(Stream.scala:519)
>	at
>net.stoerr.grokconstructor.matcher.MatcherEntryView.net$stoerr$grokconstructor$matcher$MatcherEntryView$$longestMatchOfRegexPrefix(MatcherEntryView.scala:127)
>	at
>net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$showResult$1.apply(MatcherEntryView.scala:76)
>	at
>net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$showResult$1.apply(MatcherEntryView.scala:71)
>	at
>scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
>	at
>scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
>	at
>scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
>	at
>scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
>	at
>scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
>	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
>	at
>net.stoerr.grokconstructor.matcher.MatcherEntryView.showResult(MatcherEntryView.scala:71)
>	at
>net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$result$1.apply(MatcherEntryView.scala:61)
>	at
>net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$result$1.apply(MatcherEntryView.scala:61)
>	at scala.Option.map(Option.scala:146)
>	at
>net.stoerr.grokconstructor.matcher.MatcherEntryView.result(MatcherEntryView.scala:61)
>	at
>net.stoerr.grokconstructor.webframework.WebView$class.body(WebView.scala:34)
>	at
>net.stoerr.grokconstructor.webframework.WebViewWithHeaderAndSidebox.body(WebViewWithHeaderAndSidebox.scala:10)
>	at
>net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:60)
>	at
>net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:33)
>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
>	at
>org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
>	at
>org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
>	at
>com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
>	at
>org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
>	at
>com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
>	at
>org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
>	at
>com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
>	at
>org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
>	at
>com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
>	at
>org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
>	at
>org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
>	at
>org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
>	at
>org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
>	at
>org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
>	at
>org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
>	at
>com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
>	at
>org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
>	at org.mortbay.jetty.Server.handle(Server.java:326)
>	at
>org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
>	at
>org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
>	at
>com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
>	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
>	at
>com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
>	at
>com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:693)
>	at
>com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:655)
>	at
>com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:625)
>	at
>com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:455)
>	at
>com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:462)
>	at
>com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)
>	at
>com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:321)
>	at
>com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:313)
>	at
>com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:459)
>	at
>com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
>	at java.lang.Thread.run(Thread.java:745)
>
>
>Any needful help or idea to build the requirements
>
>Regards,
>
>--jafar

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by stoerr** [comment]
Thank you for reporting this!

I cannot do much about this since here the algorithm just takes too long - the only thing you can do is to add more log lines since that makes the search space smaller, as I discussed in the description. But it should have a sensible error message, of course.

**Comment by stoerr** [comment]
I put in a more sensible error message, and made the hint to put in several log distinct messages at the same time for the construction process more visible, which probably helps in many cases.
