### ISSUE TITLE
page crash on word incremental matcher

### ISSUE THREAD

**Issue by ibigpapa** [stoerr/GrokConstructor#42]
input lines
```
LogSquad: Found USQLevel Count : 21
LogSquad: Found USQLayer Count : 191
```

1. click go
2. use radio string matching `»LogSquad:·Found·USQ«` 
3. click continue
4. fill in text box `Optional: give name for the grok expression to retrieve it's match value` with `count_type`
5. use radio grok pattern ` %{WORD}` 
6. click continue
7. Crash occurs
```
OUCH!
I'm sorry, but you have encountered a bug or missing nice display of an error message in the application. If you can't guess the problem from the error message, please contact Hans-Peter Störr (www.stoerr.net yu4cheem@techno.ms) with a copy of this page, or open an issue on https://github.com/stoerr/GrokConstructor/issues .

Please remember that you can always press the back button to fix what was wrong - there is no state on the server, only in the page shown in the browser.

      

Error message: java.util.NoSuchElementException: None.get

Time: Sun Apr 11 18:32:31 UTC 2021

RequestId: null

Request Info:
ReqInfo for 607340bf00ff0639f41e296a820001737e67726f6b636f6e7374727563746f7200013600010104 : {
  "_url":"/do/constructionstep",
  "groklibs":[
    "firewalls",
    "aws",
    "bro",
    "exim",
    "bind",
    "haproxy",
    "linux-syslog",
    "squid",
    "mcollective-patterns",
    "bacula",
    "postgresql",
    "java",
    "maven",
    "grok-patterns",
    "httpd",
    "redis",
    "nagios",
    "rails",
    "mongodb",
    "ruby",
    "mcollective",
    "junos"
  ],
  "loglines":[
    "LogSquad: Found USQLevel Count : 21\r\nLogSquad: Found USQLayer Count : 191"
  ],
  "nameOfNextPart":[
    "count_type"
  ],
  "nextPart":[
    "%{WORD}"
  ],
  "pattern":[
    "\\ALogSquad: Found USQ",
    "\\ALogSquad: Found USQ"
  ],
  "submit":[
    "Continue!"
  ]
}


java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$2.apply(IncrementalConstructionStepView.scala:28)
	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView$$anonfun$2.apply(IncrementalConstructionStepView.scala:26)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView.(IncrementalConstructionStepView.scala:25)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.giveView(WebDispatcher.scala:81)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:53)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:33)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1780)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1767)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:216)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:782)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:745)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:715)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:261)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stoerr** [comment]
Thank you for reporting this! That should have a more sensible error message, indeed. I'm closing this to clean up, since it's the same problem as https://github.com/stoerr/GrokConstructor/issues/39 .
