### ISSUE TITLE
Crash | Ouch

### ISSUE THREAD

**Issue by maltewhiite** [stoerr/GrokConstructor#43]
Error message: com.google.apphosting.api.DeadlineExceededException: This request (0000017ceb14f022) started at 2021/11/04 13:13:10.434 UTC and was still executing at 2021/11/04 13:14:11.274 UTC.
```

Time: Thu Nov 04 13:14:11 UTC 2021

RequestId: null

Request Info:
ReqInfo for 6183dc4f00ff0d15efcfea2f760001737e67726f6b636f6e7374727563746f72000136000100 : {
  "_url":"/do/match",
  "grokadditional":[
    "PROBEINTERFACE \\[(%{PATH},?\\s)\\]"
  ],
  "groklibs":[
    "firewalls",
    "aws",
    "bro",
    "exim",
    "bind",
    "haproxy",
    "linux-syslog",
    "squid",
    "mcollective-patterns",
    "bacula",
    "postgresql",
    "java",
    "maven",
    "grok-patterns",
    "httpd",
    "redis",
    "nagios",
    "rails",
    "mongodb",
    "ruby",
    "mcollective",
    "junos"
  ],
  "loglines":[
    "Most recent unsynchronized folders for probe7001: []\r\nMost recent unsynchronized folders for probe2040: [[/srv/probeinterface/./logs/1636023125]]\r\nMost recent unsynchronized folders for probe0058: [[/srv/probeinterface/./logs/1636031185, /srv/probeinterface/./logs/1636031275]]"
  ],
  "pattern":[
    "\\AMost recent unsynchronized folders for %{HOSTNAME:probe}: \\[%{PROBEINTERFACE}\\]"
  ],
  "submit":[
    "Go!"
  ]
}
```

com.google.apphosting.api.DeadlineExceededException: This request (0000017ceb14f022) started at 2021/11/04 13:13:10.434 UTC and was still executing at 2021/11/04 13:14:11.274 UTC.
```
	at org.joni.ByteCodeMachine.matchAt(ByteCodeMachine.java:272)
	at org.joni.Matcher.matchCheck(Matcher.java:304)
	at org.joni.Matcher.searchInterruptible(Matcher.java:457)
	at org.joni.Matcher.search(Matcher.java:318)
	at net.stoerr.grokconstructor.JoniRegex.findIn(JoniRegex.scala:72)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$showResult$1.apply(MatcherEntryView.scala:73)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$showResult$1.apply(MatcherEntryView.scala:71)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView.showResult(MatcherEntryView.scala:71)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$result$1.apply(MatcherEntryView.scala:61)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$result$1.apply(MatcherEntryView.scala:61)
	at scala.Option.map(Option.scala:146)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView.result(MatcherEntryView.scala:61)
	at net.stoerr.grokconstructor.webframework.WebView$class.body(WebView.scala:34)
	at net.stoerr.grokconstructor.webframework.WebViewWithHeaderAndSidebox.body(WebViewWithHeaderAndSidebox.scala:10)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:60)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:33)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1780)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1767)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:125)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:216)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.RequestRunner.dispatchServletRequest(RequestRunner.java:264)
	at com.google.apphosting.runtime.RequestRunner.dispatchRequest(RequestRunner.java:229)
	at com.google.apphosting.runtime.RequestRunner.run(RequestRunner.java:194)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stoerr** [comment]
Hi!

 

Thanks for the feedback! Unfortunately that's not something I can do much about; I don't have a good idea how to optimize that further. What I can recommend is adding more loglines and make them as variable as they might come. That restricts the search space for the regular expressions. If that doesn't help, you can probably only generate something by hand and try it with the matcher.

 

Best regards,

 

Hans-Peter

 
 

Gesendet: Donnerstag, 04. November 2021 um 14:15 Uhr
Von: "maltewhiite" ***@***.***>
An: "stoerr/GrokConstructor" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [stoerr/GrokConstructor] Crash | Ouch (Issue #43)


 

Error message: com.google.apphosting.api.DeadlineExceededException: This request (0000017ceb14f022) started at 2021/11/04 13:13:10.434 UTC and was still executing at 2021/11/04 13:14:11.274 UTC.


Time: Thu Nov 04 13:14:11 UTC 2021

RequestId: null

Request Info:
ReqInfo for 6183dc4f00ff0d15efcfea2f760001737e67726f6b636f6e7374727563746f72000136000100 : {
  "_url":"/do/match",
  "grokadditional":[
    "PROBEINTERFACE \\[(%{PATH},?\\s)\\]"
  ],
  "groklibs":[
    "firewalls",
    "aws",
    "bro",
    "exim",
    "bind",
    "haproxy",
    "linux-syslog",
    "squid",
    "mcollective-patterns",
    "bacula",
    "postgresql",
    "java",
    "maven",
    "grok-patterns",
    "httpd",
    "redis",
    "nagios",
    "rails",
    "mongodb",
    "ruby",
    "mcollective",
    "junos"
  ],
  "loglines":[
    "Most recent unsynchronized folders for probe7001: []\r\nMost recent unsynchronized folders for probe2040: [[/srv/probeinterface/./logs/1636023125]]\r\nMost recent unsynchronized folders for probe0058: [[/srv/probeinterface/./logs/1636031185, /srv/probeinterface/./logs/1636031275]]"
  ],
  "pattern":[
    "\\AMost recent unsynchronized folders for %{HOSTNAME:probe}: \\[%{PROBEINTERFACE}\\]"
  ],
  "submit":[
    "Go!"
  ]
}


com.google.apphosting.api.DeadlineExceededException: This request (0000017ceb14f022) started at 2021/11/04 13:13:10.434 UTC and was still executing at 2021/11/04 13:14:11.274 UTC.

	at org.joni.ByteCodeMachine.matchAt(ByteCodeMachine.java:272)
	at org.joni.Matcher.matchCheck(Matcher.java:304)
	at org.joni.Matcher.searchInterruptible(Matcher.java:457)
	at org.joni.Matcher.search(Matcher.java:318)
	at net.stoerr.grokconstructor.JoniRegex.findIn(JoniRegex.scala:72)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$showResult$1.apply(MatcherEntryView.scala:73)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$showResult$1.apply(MatcherEntryView.scala:71)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView.showResult(MatcherEntryView.scala:71)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$result$1.apply(MatcherEntryView.scala:61)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView$$anonfun$result$1.apply(MatcherEntryView.scala:61)
	at scala.Option.map(Option.scala:146)
	at net.stoerr.grokconstructor.matcher.MatcherEntryView.result(MatcherEntryView.scala:61)
	at net.stoerr.grokconstructor.webframework.WebView$class.body(WebView.scala:34)
	at net.stoerr.grokconstructor.webframework.WebViewWithHeaderAndSidebox.body(WebViewWithHeaderAndSidebox.scala:10)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:60)
	at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:33)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1780)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1767)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:125)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:216)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.RequestRunner.dispatchServletRequest(RequestRunner.java:264)
	at com.google.apphosting.runtime.RequestRunner.dispatchRequest(RequestRunner.java:229)
	at com.google.apphosting.runtime.RequestRunner.run(RequestRunner.java:194)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:748)


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by maltewhiite** [comment]
Hi.

No worries. I just wanted to provide the log for you.
Thanks a lot for providing this great website and the services it 
contains.
It is a massive help, while building Logstash filters.

**Comment by stoerr** [comment]
Hi!

Thank you for the praise! That’s a rare thing that somebody says something. :-)

Best regards,

Hans-Peter

**Comment by stoerr** [comment]
Thank you for reporting this!

I cannot do anything about this since here the algorithm just takes too long - the only thing you can do is to add more log lines since that makes the search space smaller. But it should have a sensible error message, of course. But to clean up, I'm closing this one since that's the same problem as https://github.com/stoerr/GrokConstructor/issues/35 and would be fixed at the same time.
