### ISSUE TITLE
Error message: org.joni.exception.SyntaxException: unmatched close parenthesis

### ISSUE THREAD

**Issue by juniorsemacento** [stoerr/GrokConstructor#7]
Error message: org.joni.exception.SyntaxException: unmatched close parenthesis

Request Info:
http://grokconstructor.appspot.com/do/constructionstep?null:
{"grokadditional":[""],"submit":["Continue!"],"pattern":["\A%{SYSLOG5424PRINTASCII} %{LOGLEVEL} \(%{BASE10NUM}"],"multiline":[""],"nameOfNextPart":[""],"loglines":["2015-07-22T08:21:27-04:00 NOTICE (5): [ACCESS GRANTED] /pusher/auth [e98fc7bf73eb62c4ad43dd4f1a1b8e75] &socket_id=47627.2019085&channel_name=presence-b703843ae8f14d53baa504db70c0b51d"],"nextPartPerHand":[""],"groklibs":["firewalls","haproxy","linux-syslog","mcollective-patterns","postgresql","java","grok-patterns","redis","nagios","mongodb","ruby","mcollective","junos"],"nextPart":["): \["]}

org.joni.exception.SyntaxException: unmatched close parenthesis
    at org.joni.ScannerSupport.newSyntaxException(ScannerSupport.java:166)
    at org.joni.Parser.parseExp(Parser.java:672)
    at org.joni.Parser.parseBranch(Parser.java:962)
    at org.joni.Parser.parseSubExp(Parser.java:979)
    at org.joni.Parser.parseRegexp(Parser.java:1012)
    at org.joni.Parser.parse(Parser.java:64)
    at org.joni.Analyser.compile(Analyser.java:83)
    at org.joni.Regex.(Regex.java:162)
    at org.joni.Regex.(Regex.java:139)
    at org.joni.Regex.(Regex.java:125)
    at org.joni.Regex.(Regex.java:109)
    at net.stoerr.grokconstructor.JoniRegex.(JoniRegex.scala:16)
    at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView.(IncrementalConstructionStepView.scala:22)
    at net.stoerr.grokconstructor.webframework.WebDispatcher.giveView(WebDispatcher.scala:58)
    at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:32)
    at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:26)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:482)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:234)
    at java.lang.Thread.run(Thread.java:745)

**Comment by ghost** [comment]
OUCH!

I'm sorry, but you have encountered a bug or missing nice display of an error message in the application. If you can't guess the problem from the error message, please contact Hans-Peter Störr (www.stoerr.net yu4cheem@techno.ms) with a copy of this page, or open an issue on https://github.com/stoerr/GrokConstructor/issues .

Please remember that you can always press the back button to fix what was wrong - there is no state on the server, only in the page shown in the browser.

Error message: org.joni.exception.SyntaxException: unmatched close parenthesis

Request Info:
http://grokconstructor.appspot.com/do/constructionstep?null:
{"grokadditional":[""],"submit":["Continue!"],"pattern":["\A%{TIMESTAMP_ISO8601} %{LOGLEVEL}%{SPACE}\[%{PROG}] \(%{PROG}"],"multiline":[""],"nameOfNextPart":[""],"loglines":["2015-10-13 15:45:28,255 INFO  [org.cas.oscar.server.services.savedanswerset.SavedAnswerSetService](http-jbat-aps51-0003%2F134.243.80.58-8180-25) (userName=ygangasa sessionId=62836836X86F35092X118BD0F13D9FCECF28 sequenceNumber=27) Exiting 'save'\r\n2015-10-13 15:45:28,255 ERROR [org.cas.osd.sfweb.session.SessionPersistence](http-jbat-aps51-0003%2F134.243.80.58-8180-25) (userName=ygangasa sessionId=62836836X86F35092X118BD0F13D9FCECF28 sequenceNumber=27) Error autosaving answer set during logout\r\n2015-10-13 15:45:28,289 INFO  [org.cas.oscar.server.services.session.SessionStateRepositoryFactory](jmsContainer-1) (userName= sessionId= sequenceNumber=) read SessionState@a84eb9e(MoiService[ver=63]@mrs51:134.243.85.56:58472:101508:2) (62836836X86F35092X118BD0F13D9FCECF28)"],"nextPartPerHand":[""],"groklibs":["grok-patterns"],"nextPart":[") \("]}

org.joni.exception.SyntaxException: unmatched close parenthesis
    at org.joni.ScannerSupport.newSyntaxException(ScannerSupport.java:166)
    at org.joni.Parser.parseExp(Parser.java:672)
    at org.joni.Parser.parseBranch(Parser.java:962)
    at org.joni.Parser.parseSubExp(Parser.java:979)
    at org.joni.Parser.parseRegexp(Parser.java:1012)
    at org.joni.Parser.parse(Parser.java:64)
    at org.joni.Analyser.compile(Analyser.java:83)
    at org.joni.Regex.(Regex.java:162)
    at org.joni.Regex.(Regex.java:139)
    at org.joni.Regex.(Regex.java:125)
    at org.joni.Regex.(Regex.java:109)
    at net.stoerr.grokconstructor.JoniRegex.(JoniRegex.scala:16)
    at net.stoerr.grokconstructor.incremental.IncrementalConstructionStepView.(IncrementalConstructionStepView.scala:22)
    at net.stoerr.grokconstructor.webframework.WebDispatcher.giveView(WebDispatcher.scala:58)
    at net.stoerr.grokconstructor.webframework.WebDispatcher.doGet(WebDispatcher.scala:32)
    at net.stoerr.grokconstructor.webframework.WebDispatcher.doPost(WebDispatcher.scala:26)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:147)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:457)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
    at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
    at java.lang.Thread.run(Thread.java:745)

**Comment by stoerr** [comment]
In both cases it seems there was something broken with the quoting of the fixed String. I can't reproduce this anymore, so I assume I fixed this in the meantime. :-)
